### PR TITLE
don't import Moo::Role for plugin2 compatibility

### PR DESCRIPTION
**Pull request by SysPete**
In current D2 release Plugin class is a Moo::Role but in next release it is a full Moo class so importing Moo::Role breaks plugin with current dev releases (and next full release).

### CODE REVIEW

**Comment by zurborg** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was 015a08d8684963ba05f975b06c48176a73b51780, new (rebased) HEAD is adcd208a03d45b7e09c3c88a4940dc84671c5308

**Comment by zurborg** [comment]
TravisCI do not compile Dancer2 with perl 5.10 and 5.12 - but with 5.14 and later everything seems to be fine.

**Comment by SysPete** [comment]
@zurborg this is a regression since we _try_ to keep compatibility with 5.8. I'll check it out tomorrow. Thanks for heads up.

**Comment by SysPete** [comment]
@zurborg 5.10 and 5.12 failures caused by travis trying (and failing) to install Dist::Zilla 6.x which requires 5.14+

Travis environments come complete with an earlier dzil so perhaps just removing the dzil install from travis.yml is the simplest fix.

**Comment by zurborg** [comment]
Some dzil plugins require a newer version of Dist::Zilla, so that will be installed anyway. I'm not able to test this plugin against perl-5.8/10/12 with TravisCI. Sorry.

**Pull request closed without merging**
